apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: ev_postgres
    url: postgresdb:5432
    user: postgres
    secureJsonData:
      password: strongpassword
    jsonData:
      database: ev
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600       # Postgres 16
      timescaledb: false
    isDefault: true
    editable: true
